Step 3 - Implementing abstract generative api
* Add GenerativeGeneration interface

public interface GenerativeGeneration<T> {

    T getOutput();

    GenerationMetadata getGenerationMetadata();
}

* Refactor class generation to be

public class Generation implements GenerativeGeneration<AssistantMessage> {

	private AssistantMessage assistantMessage;

	private GenerationMetadata generationMetadata;

}

* Rename GenerationMeadata to ChatGenerationMetadata

* Add marker interface public interface GenerationMetadata {}

* Move metadata package under chat package for now as it is very specific to chat use cases.

* Add JAvadocs to generative and chat package.

== TODO ==
Need more work on 'portable' ResponseMetadata and GenerationMetadata
Maybe in AbstactMessage

protected String content;

public String getContent() {
		return this.content;
}

At the moment changing getContent to  getText() would be more legible since it is returning 'text' as a datatype as compared to 'content' which sounds generic and 'output' is already generic.  Maybe in the future we will introduce generics into the Message class, in that case getContent is better, the content returned could be an image insteady of text.  NEed to see what multi-model responses would be like.  Keep getContent for now.

Getting Build error on tests

 java.io.FileNotFoundException: class path resource [embedding/embedding-generative-dimensions.properties] cannot be opened because it does not exist [in thread "main"]